PartialModule/Controllers/KbaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartialModule.Controllers
{
    public class KbaseController : Controller
    {
        // GET: Kbase 提交选编
        public ActionResult Index()
        {
            return View();
        }
    }
}

PartialModule/Controllers/RapidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartialModule.Controllers
{
    public class RapidController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 发布列表
        /// </summary>
        /// <returns></returns>
        public ActionResult ListToPublish()
        {
            var data = TempData["datas"] as List<string> ?? new List<string>();
            TempData["datas"] = data;
            return PartialView(data);
        }

        /// <summary>
        /// 发布列表数据的增删
        /// </summary>
        /// <param name="isAdd">true:增；false:删</param>
        /// <param name="datas"></param>
        /// <returns></returns>
        public JsonResult AddOrRemove(bool isAdd, List<string> datas = null)
        {
            var items = TempData["datas"] as List<string> ?? new List<string>();
            if (isAdd)
            {
                if (datas != null && datas.Count > 0)
                    items.AddRange(datas);
            }
            else
            {
                if (items.Count > 0)
                {
                    items.Remove(items.LastOrDefault());
                }
            }

            TempData["datas"] = items;
            return Json(new { result = true }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult RemoveLast()
        {
            var datas = TempData["datas"] as List<string>??new List<string>();
            if(datas.Count>0)
            datas.RemoveAt(datas.Count - 1);

            TempData["datas"] = datas;
            return Json(new { result = datas});
        }

    }
}

PartialModule/Controllers/TCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartialModule.Controllers
{
    public class TCController : Controller
    {
        // GET: TC 统采数据
        //[ChildActionOnly]
        public ActionResult Index()
        {
            return PartialView();
        }
    }
}

PartialModule/Controllers/ZCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartialModule.Controllers
{
    public class ZCController : Controller
    {
        // GET: ZC 自采数据,后期需要改为外界不可直接访问
        /// <summary>
        /// 自采数据首页
        /// </summary>
        /// <param name="from">请求来源</param>
        /// <param name="data">自定义的用于显示目标数据的结构体</param>
        /// <returns></returns>
        [HttpPost]
        
        public ActionResult Index(string from, object data = null)
        {
            ViewBag.From = from;
            ViewBag.Data = data;
            ViewBag.Test = "admin Tests";
            return PartialView();
        }
    }
}

PartialModule/Views/Kbase/Index.cshtml
@{
    ViewBag.Title = "提交选编";
}
<input id="PageIndex" value="@Html.ViewContext.RouteData.Values["controller"]" hidden />
<ul id="myTab" class="nav nav-tabs" style="margin-top:70px;margin-left:3%;margin-bottom: 0px;">
    <li class="active">
        <a class="zckf" href="#ZCKF" data-toggle="tab">
            自采数据
        </a>
    </li>
    <li><a class="tckf" href="#TCKF" data-toggle="tab">统采数据</a></li>
    <li><a class="sjsh" href="#SJSH" data-toggle="tab">数据审核</a></li>
    <li><a class="sjpc" href="#SJPC" data-toggle="tab">数据排重</a></li>
</ul>
<div class="content" style="margin-top:0px;padding: 0 0 30px;background-color: #f7f7f7;">
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="ZCKF" style="font-size:15px;"></div>
        <div class="tab-pane fade" id="TCKF"></div>
        <div class="tab-pane fade" id="SJSH"></div>
        <div class="tab-pane fade" id="SJPC">数据排重</div>
    </div>
</div>
<script type="text/javascript">
    $(function () {

        $(".zckf").click();
    });
    $('#myTab a').on('click', function (e) {
        var target = e.currentTarget.className;
        switch (target)
        {
            case 'zckf':
                var postData = new Object();
                postData.from = $("#PageIndex").val();
                postData.data = null;
                $.ajax({
                    url: "/ZC/Index",
                    data: JSON.stringify(postData),//传给服务器的数据(即后台AddUsers()方法的参数,参数类型要一致才可以)
                    type: 'POST',
                    contentType: 'application/json;charset=utf-8',//数据类型必须有
                    success: function (data) //成功后的回调方法
                    {
                        $("#ZCKF").html(data)
                    },
                    error: function (data) {
                        alert("失败:" + data[0])//弹出框
                    }

                });
                break;
            case 'tckf':
                $.ajax({
                    url: "/TC/Index",
                    data: null,//传给服务器的数据(即后台AddUsers()方法的参数,参数类型要一致才可以)
                    type: 'GET',
                    //contentType: 'application/json;charset=utf-8',//数据类型必须有
                    success: function (data) //成功后的回调方法
                    {
                        $("#TCKF").html(data);
                    },
                    error: function (data) {
                        alert("失败:" + data[0])//弹出框
                    }

                });
                break;
            case 'sjsh':
                // 清空其他模块内容，避免脚本、样式等相互影响
                // 加载快发列表模块
                $("#SJSH").html("数据审核");
                
                break;
            //case 'kf_log':
            //    $("#KF_log").html("历史记录");
            //    break;
            //case 'kf_log_del':
            //    $("#KF_log_del").html("删除日志");
            //    break;
        }
    });
</script>

PartialModule/Views/Rapid/Index.cshtml
@using System.Dynamic
@{
    ViewBag.Title = "快发数据";
}
<input id="PageIndex" value="@Html.ViewContext.RouteData.Values["controller"]" hidden />
<ul id="myTab" class="nav nav-tabs" style="margin-top:70px;margin-left:3%;margin-bottom: 0px;">
    <li class="active"><a class="zckf" href="#ZCKF" data-toggle="tab">自采数据</a></li>
    <li><a class="tckf" href="#TCKF" data-toggle="tab">统采数据</a></li>
    <li><a class="kf_list" href="#KF_list" data-toggle="tab">发布列表</a></li>
    <li><a class="kf_log" href="#KF_log" data-toggle="tab">历史记录</a></li>
    <li><a class="kf_log_del" href="#KF_log_del" data-toggle="tab">删除日志</a></li>
</ul>

<div class="content" style="margin-top:0px;padding: 0 0 30px;background-color: #f7f7f7;">
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="ZCKF"></div>
        <div class="tab-pane fade" id="TCKF"></div>
        <div class="tab-pane fade" id="KF_list"></div>
        <div class="tab-pane fade" id="KF_log">历史记录</div>
        <div class="tab-pane fade" id="KF_log_del">删除日志</div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $(".zckf").click();
    });
    $('#myTab a').on('click', function (e) {
        var target = e.currentTarget.className;
        switch (target)
        {
            case 'zckf':
                var postData = new Object();
                postData.from = $("#PageIndex").val();
                postData.data = null;
                $.ajax({
                    url: "/ZC/Index",
                    data: JSON.stringify(postData),//传给服务器的数据(即后台AddUsers()方法的参数,参数类型要一致才可以)
                    type: 'POST',
                    contentType: 'application/json;charset=utf-8',//数据类型必须有
                    success: function (data) //成功后的回调方法
                    {
                        $("#ZCKF").html(data)
                    },
                    error: function (data) {
                        alert("失败:" + data[0])//弹出框
                    }

                });
                break;
            case 'tckf':
                $.ajax({
                    url: "/TC/Index",
                    data: null,//传给服务器的数据(即后台AddUsers()方法的参数,参数类型要一致才可以)
                    type: 'GET',
                    //contentType: 'application/json;charset=utf-8',//数据类型必须有
                    success: function (data) //成功后的回调方法
                    {
                        $("#TCKF").html(data);
                    },
                    error: function (data) {
                        alert("失败:" + data[0])//弹出框
                    }

                });
                break;
            case 'kf_list':
                // 清空其他模块内容，避免脚本、样式等相互影响
                // 加载快发列表模块
                $.ajax({
                    url: "/Rapid/ListToPublish",
                         data: '',//传给服务器的数据(即后台AddUsers()方法的参数,参数类型要一致才可以)
                         type: 'GET',
                         success: function (data) //成功后的回调方法
                         {
                             $("#KF_list").html(data)
                         },
                         error: function (data) {
                             alert("失败:" + data[0])//弹出框
                         }

                 });
                break;
            //case 'kf_log':
            //    $("#KF_log").html("历史记录");
            //    break;
            //case 'kf_log_del':
            //    $("#KF_log_del").html("删除日志");
            //    break;
        }
    });
</script>

PartialModule/Views/Rapid/ListToPublish.cshtml
<h2>发布列表</h2>
@model List<string>

<div class="DataList">
    @{
        foreach (var item in Model)
        {
            <text>@item</text><br />
        }
    }
</div>

<div>&nbsp;</div>
<button type="button" class="btn-glow Release btn_jb_color">
    <i class="icon-bookmark"></i> 清除最后一条
</button>

<button type="button" class="btn-glow lookback btn_jb_color">
    <i class="icon-bookmark"></i> 数据回看
</button>

<script type="text/javascript">
    $(".Release").click(function () {
        $.ajax({
            url: '@Url.Action("RemoveLast", "Rapid")',//控制器活动,返回一个分部视图,并且给分部视图传递数据.
            data: '',
            type: 'POST',
            contentType: 'application/json;charset=utf-8',//数据类型必须有
            success: function (data) //成功后的回调方法
            {
                $(".DataList").html("");
                var datas = data.result;
                for (let item in datas) {
                    console.log(item);
                    $(".DataList").append(datas[item]);
                }; 
                //$("#myDiv").html(data);//data--就是对应的分部视图页面内容.
               // alert(data.result)//弹出框
            },
            error: function (data) {
                alert("失败:" + data[0])//弹出框
            }

        });
    });

    $(".lookback").click(function () {
        //$(".zckf").click();

        // 直接切换选中状态
        // 通过ajax更新对应标签下的内容
        var postData = new Object();
        postData.from = '@Html.ViewContext.RouteData.Values["controller"]';
        postData.data = "发布列表中看到的数据";


        //alert("Not Implement Exception");
        $.ajax({
            url: '@Url.Action("Index", "ZC")',//控制器活动,返回一个分部视图,并且给分部视图传递数据.
            data: JSON.stringify(postData),
            type: 'POST',
            contentType: 'application/json;charset=utf-8',//数据类型必须有
            success: function (data) //成功后的回调方法
            {
                $("#ZCKF").html(data);//data--就是对应的分部视图页面内容.
                $(".zckf").parent().addClass("active");
                $("#ZCKF").addClass(" in active");
                $("#KF_list").removeClass(" in active");
                $(".kf_list").parent().removeClass("active");
               // alert(data.result)//弹出框
            },
            error: function (data) {
                alert("失败:" + data[0])//弹出框
            }
        
        });
    });
</script>

PartialModule/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("快速发布", "Index", "Rapid")</li>
                    <li>@Html.ActionLink("提交选编", "Index", "Kbase")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

PartialModule/Views/TC/Index.cshtml
<h2>统采数据</h2>
<script type="text/javascript">
    $(function () {
        // update page title
        //$(document).attr("title", "统采");
    });
</script>